//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseGO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ActivityLog
    {
        public int ActivityLogID { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public System.DateTime LogDate { get; set; }
        public Nullable<int> TotalReps { get; set; }
        public Nullable<int> TotalSets { get; set; }
        public string Notes { get; set; }
        public string AspNetUserID { get; set; }
        public int TargetAreaID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual TargetArea TargetArea { get; set; }
    }
}
