//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoID { get; set; }
        public string VideoName { get; set; }
        public bool IsWatch { get; set; }
        public bool IsBonus { get; set; }
        public int TargetAreaID { get; set; }
        public int VideoStart { get; set; }
        public int VideoEnd { get; set; }
        public string VideoLink { get; set; }
    
        public virtual TargetArea TargetArea { get; set; }
    }
}
